# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='字段名')),
                ('alias', models.CharField(max_length=20, null=True, unique=True, verbose_name='别名')),
                ('readme', models.TextField(blank=True, default='', verbose_name='自述')),
                ('type', models.SmallIntegerField(choices=[(0, 'string'), (1, 'integer'), (2, 'floating'), (3, 'datetime')], verbose_name='字段类型')),
                ('is_multi', models.BooleanField(default=False, verbose_name='是否为多值字段')),
                ('required', models.BooleanField(default=False, verbose_name='是否必填')),
            ],
        ),
        migrations.CreateModel(
            name='RestPWVerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='表名')),
                ('alias', models.CharField(max_length=20, null=True, unique=True, verbose_name='别名')),
                ('readme', models.TextField(blank=True, default='', verbose_name='自述')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mgmt.Table', verbose_name='字段'),
        ),
    ]
