# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='表名'),
        ),
    ]
